# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# Build documentation with Sphinx.
sphinx:
  configuration: docs/conf.py

# Set the version of Python and requirements required to build the docs.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - visualize
        - dev
