site_name: pyribs
copyright: "Copyright &copy; 2020 ICAROS Lab"
site_url: https://ribs.readthedocs.io
repo_url: https://github.com/icaros-usc/pyribs
repo_name: icaros-usc/pyribs
nav:
  - Home: index.md
  - API:
      - ribs.config: ribs.config.md
      - ribs.archives: ribs.archives.md
      - ribs.emitters: ribs.emitters.md
      - ribs.optimizers: ribs.optimizers.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      watch:
        - ribs
      handlers:
        python:
          rendering:
            show_object_full_path: False
theme:
  name: material
  palette:
    primary: indigo
  logo: img/outdoor_grill.svg
  favicon: img/outdoor_grill.svg
extra_css:
  - css/mkdocstrings.css
