"""Provides the IsoLineEmitter and corresponding IsoLineEmitterconfig."""

import numpy as np

from ribs.config import create_config


class IsoLineEmitterConfig:
    """Configuration for the IsoLineEmitter.

    Args:
        seed (float or int): Value to seed the random number generator. Set to
            None to avoid seeding. Default: None
        batch_size (int): Number of solutions to send back in the ask() method.
            Default: 64
    """

    def __init__(
        self,
        seed=None,
        batch_size=64,
    ):
        self.seed = seed
        self.batch_size = batch_size


class IsoLineEmitter:
    """Attempts to emit solutions from the same hypervolume as existing elites.

    If the archive is empty, calls to ask() will generate solutions from an
    isotropic Gaussian distribution with mean ``x0`` and standard deviation
    ``iso_sigma``. Otherwise, to generate each new solution, the emitter selects
    a pair of elites :math:`x_i` and :math:`x_j` and samples from

    .. math::

        x_i + \\sigma_{iso} \\mathcal{N}(0,\\mathcal{I}) +
            \\sigma_{line}(x_j - x_i)\\mathcal{N}(0,1)

    This emitter is based on the operator presented in this paper:
    https://arxiv.org/abs/1804.03906

    Args:
        x0 (array-like): Center of the Gaussian distribution from which to
            sample solutions when the archive is empty.
        archive (ribs archive): An archive to use when creating and inserting
            solutions. For instance, this can be
            :class:`ribs.archives.GridArchive`.
        iso_sigma (float): Scale factor for the isotropic distribution used when
            generating solutions.
        line_sigma (float): Scale factor for the line distribution used when
            generating solutions.
        config (None or dict or IsoLineEmitterConfig): Configuration object. If
            None, a default IsoLineEmitterConfig is constructed. A dict may
            also be passed in, in which case its arguments will be passed into
            IsoLineEmitterConfig.
    Attributes:
        config (IsoLineEmitterConfig): Configuration object.
        x0 (np.ndarray): See args.
        iso_sigma (float): See args.
        line_sigma (float): See args.
        archive (ribs archive): See args.
        batch_size (int): Number of solutions to generate on each call to ask().
            Passed in via ``config.batch_size``.
    """

    def __init__(self,
                 x0,
                 archive,
                 iso_sigma=0.01,
                 line_sigma=0.2,
                 config=None):
        self.config = create_config(config, IsoLineEmitterConfig)
        self._rng = np.random.default_rng(self.config.seed)

        self.x0 = np.array(x0)
        self.iso_sigma = iso_sigma
        self.line_sigma = line_sigma
        self.archive = archive
        self.batch_size = self.config.batch_size

    def ask(self):
        """Generates ``self.batch_size`` solutions.

        If the archive is empty, solutions are drawn from an isotropic Gaussian
        distribution centered at ``self.x0`` with standard deviation
        ``self.iso_sigma``. Otherwise, each solution is drawn as described in
        this class's docstring.

        Returns:
            ``(self.batch_size, len(self.x0))`` array -- contains ``batch_size``
            new solutions to evaluate.
        """
        if self.archive.is_empty():
            return np.expand_dims(self.x0, axis=0) + self._rng.normal(
                scale=self.iso_sigma, size=(self.batch_size, len(self.x0)))

        parents = [
            self.archive.get_random_elite()[0] for _ in range(self.batch_size)
        ]
        directions = [(self.archive.get_random_elite()[0] - parents[i])
                      for i in range(self.batch_size)]
        iso_gaussian = self._rng.normal(scale=self.iso_sigma,
                                        size=(self.batch_size, len(self.x0)))
        line_gaussian = self._rng.normal(scale=self.line_sigma,
                                         size=(self.batch_size, 1))
        return parents + iso_gaussian + line_gaussian * directions

    def tell(self, solutions, objective_values, behavior_values):
        """Gives the emitter results from evaluating several solutions.

        These solutions are then inserted into the archive.

        Args:
            solutions (np.ndarray): Array of solutions generated by this
                emitter's :meth:`ask()` method.
            objective_values (np.ndarray): 1D array containing the objective
                function value of each solution.
            behavior_values (np.ndarray): ``(n, <behavior space dimension>)``
                array with the behavior space coordinates of each solution.
        """
        for sol, obj, beh in zip(solutions, objective_values, behavior_values):
            self.archive.add(sol, obj, beh)
