#!/usr/bin/env python
#
# ribs documentation build configuration file, created by
# sphinx-quickstart.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
#
# pylint: skip-file
# isort: skip-file

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
import datetime
import os
import sys

import sphinx_material

import ribs

sys.path.insert(0, os.path.abspath(".."))  # Detect ribs.
sys.path.append(os.path.abspath("./_ext"))  # Detect extensions.

# Set canonical URL from the Read the Docs Domain
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "")

DEV_MODE = os.environ.get("DOCS_MODE", "regular") == "dev"
READTHEDOCS_VERSION = os.environ.get("READTHEDOCS_VERSION", "stable")
READTHEDOCS_LANGUAGE = os.environ.get("READTHEDOCS_LANGUAGE", "en")

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = "4.5.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx.ext.intersphinx",
    "sphinx_material",
    "sphinx_copybutton",
    "myst_nb",  # Covers both Markdown files and Jupyter notebooks.
    "matplotlib.sphinxext.plot_directive",
    "sphinx_toolbox.more_autodoc.autonamedtuple",
    "sphinx_autodoc_typehints",
    "sphinx_codeautolink",
    "github_links",
]

# Napoleon
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_use_param = True  # see tox-dev/sphinx-autodoc-typehints#15
napoleon_use_ivar = True
napoleon_include_special_with_doc = True

# MyST NB -- exclude execution of Jupyter notebooks because they can take a
# while to run.
nb_execution_mode = "off"

# https://github.com/executablebooks/MyST-NB/issues/441
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
]
# Auto-generate heading anchors.
myst_heading_anchors = 3

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md", ".ipynb"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "pyribs"
copyright = f"2021-{datetime.datetime.now().year}, ICAROS Lab"
author = "ICAROS Lab pyribs Team"

# The version info for the project you"re documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = ribs.__version__
# The full version, including alpha/beta/rc tags.
release = ribs.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
#  pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

github_repo_url = "https://github.com/icaros-usc/pyribs/"

# -- Options for HTML output -------------------------------------------

html_show_sourcelink = True
html_sidebars = {"**": ["globaltoc.html", "localtoc.html", "searchbox.html"]}

html_theme_path = sphinx_material.html_theme_path()
html_context = sphinx_material.get_html_context()
html_theme = "sphinx_material"
html_logo = "_static/imgs/icon.svg"
html_favicon = "_static/imgs/favicon.ico"
html_title = (
    f"pyribs (stable - v{version})"
    if READTHEDOCS_VERSION == "stable"
    else f"pyribs ({READTHEDOCS_VERSION})"
)

# Tell Jinja2 templates the build is running on Read the Docs
if os.environ.get("READTHEDOCS", "") == "True":
    html_context["READTHEDOCS"] = True

# material theme options (see theme.conf for more information)
html_theme_options = {
    "nav_title": "pyribs",
    "base_url": (
        f"https://docs.pyribs.org/{READTHEDOCS_LANGUAGE}/{READTHEDOCS_VERSION}/"
    ),
    "repo_url": github_repo_url,
    "repo_name": "pyribs",
    "google_analytics_account": None,
    "html_minify": not DEV_MODE,
    "css_minify": not DEV_MODE,
    #  "logo_icon": "&#xe869",
    "repo_type": "github",
    # Needs to be 3 so that tutorials show up in sidebar.
    "globaltoc_depth": 3,
    "color_primary": "deep-purple",
    "color_accent": "purple",
    "touch_icon": None,
    "master_doc": False,
    "nav_links": [
        {"href": "index", "internal": True, "title": "Home"},
    ],
    "heroes": {
        "index": "A bare-bones Python library for quality diversity optimization."
    },
    "version_dropdown": True,
    "version_json": None,
    "version_info": {
        "Stable": "https://docs.pyribs.org/en/stable/",
        "Latest": "https://docs.pyribs.org/en/latest/",
    },
    "table_classes": ["plain"],
}

html_last_updated_fmt = None

html_use_index = True
html_domain_indices = True

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = [
    "custom.css",
]

# -- Extension config -------------------------------------------------

# Autodoc and autosummary
autodoc_member_order = "groupwise"  # Can be overridden by :member-order:
autodoc_default_options = {
    "inherited-members": True,
}
autosummary_generate = True

# Matplotlib plot directive.
plot_include_source = True
plot_formats = [("png", 90)]
plot_html_show_formats = False
plot_html_show_source_link = False

# Intersphinx
intersphinx_mapping = {
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "python": ("https://docs.python.org/3/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
    "qdax": ("https://qdax.readthedocs.io/en/latest/", None),
    "shapely": ("https://shapely.readthedocs.io/en/stable/", None),
    "cma": ("https://cma-es.github.io/apidocs-pycma/", None),
}
