# Test installation from vendors like PyPI and Conda.
name: Install

on:
  schedule:
    # Every day at 2AM UTC (6PM PST, 7PM PDT)
    - cron: "0 2 * * *"

defaults:
  run:
    # The default shell must be set like this so that bash will source the
    # profile, which contains settings initialized by Conda:
    # https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -el {0}

jobs:
  test:
    strategy:
      max-parallel: 12 # All in parallel.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core deps
        run: pip install ribs[all]
      - name: Test install
        run: |
          python -c "import ribs; import ribs.visualize; print(ribs.__version__)"
